# Generated by Django 5.2.14 on 2026-05-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gacha',
            old_name='winning_num',
            new_name='winning_nums',
        ),
        migrations.AddField(
            model_name='ticket',
            name='draw',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lotto.gacha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
